### PR TITLE
Discord RPC & Formatting

### PR DESCRIPTION
**Pull request by bddylol**

### CODE REVIEW

**Comment by bddylol** [comment]
Using kat's discord client ID.

**Comment by EnZon3** [comment]
this is cool i support

**Comment by datkat21** [comment]
Your formatter settings completely destroyed trailing commas in those files but I'll be nice and fix it for you afterwards :P

**Comment by bddylol** [comment]
> Your formatter settings completely destroyed trailing commas in those files but I'll be nice and fix it for you afterwards :P

what's wrong with the trailing commas?

**Comment by datkat21** [comment]
if you look it made a ton of useless diffs that i had to dig through just to see what was changed, anyways i'll fix it in the next commit to stay within code style

**Comment by EnZon3** [comment]
also hello guys it's been a hot minute

**Comment by bddylol** [comment]
> also hello guys it's been a hot minute

r u still on discord?

**Comment by EnZon3** [comment]
> > also hello guys it's been a hot minute
> 
> 
> 
> r u still on discord?

no, i'm not. i only talk to ppl i know IRL on there

if you need anything/wanna talk PM me on ask when it reopens

**Comment by EnZon3** [comment]
@bddylol FYI i am active on AMC

**Pull request merged**
